artifact_uri: file:///E:/M_Hassan/AI_Work/StackOverflow_skills_analysis/dev_skills_recommendations-anlytics/notebooks/../models/runs/391017000133266862/b14ed70dfe1a495db99fd74ad3fc031c/artifacts
end_time: 1689773931274
entry_point_name: ''
experiment_id: '391017000133266862'
lifecycle_stage: active
run_id: b14ed70dfe1a495db99fd74ad3fc031c
run_name: 2.basic_model_with_clustered_features
run_uuid: b14ed70dfe1a495db99fd74ad3fc031c
source_name: ''
source_type: 4
source_version: ''
start_time: 1689773931242
status: 3
tags: []
user_id: mhassan
