artifact_location: file:///E:/M_Hassan/AI_Work/StackOverflow_skills_analysis/Dev_skills_recommendations-anlytics/src/data/../models/runs/290708519391319285
creation_time: 1692524676495
experiment_id: '290708519391319285'
last_update_time: 1692524676495
lifecycle_stage: active
name: skills_rec_analysis
