artifact_location: file:///D:/protofolio_projects/Dev_skills_recommendations-anlytics/notebooks/../models/runs/735982700926372623
creation_time: 1692264336720
experiment_id: '735982700926372623'
last_update_time: 1692264336720
lifecycle_stage: active
name: skills_rec_analysis
