artifact_location: file:///E:/M_Hassan/AI_Work/StackOverflow_skills_analysis/Dev_skills_recommendations-anlytics/src/data/../models/runs/0
creation_time: 1692524676480
experiment_id: '0'
last_update_time: 1692524676480
lifecycle_stage: active
name: Default
