artifact_location: file:///E:/M_Hassan/AI_Work/StackOverflow_skills_analysis/Dev_skills_recommendations-anlytics/notebooks/../models/runs/907184637109318169
creation_time: 1691500968503
experiment_id: '907184637109318169'
last_update_time: 1691500968503
lifecycle_stage: active
name: skills_rec_analysis
