artifact_location: file:///E:/M_Hassan/AI_Work/StackOverflow_skills_analysis/dev_skills_recommendations-anlytics/notebooks/../models/runs/958618704808840933
creation_time: 1690991353540
experiment_id: '958618704808840933'
last_update_time: 1690991353540
lifecycle_stage: active
name: skills_rec_analysis
