artifact_uri: file:///E:/M_Hassan/AI_Work/StackOverflow_skills_analysis/Dev_skills_recommendations-anlytics/notebooks/../models/runs/907184637109318169/f6cf7dfa383f4a89811010639556c9d7/artifacts
end_time: 1691500968772
entry_point_name: ''
experiment_id: '907184637109318169'
lifecycle_stage: active
run_id: f6cf7dfa383f4a89811010639556c9d7
run_name: 2.basic_model_with_clustered_features
run_uuid: f6cf7dfa383f4a89811010639556c9d7
source_name: ''
source_type: 4
source_version: ''
start_time: 1691500968741
status: 3
tags: []
user_id: mhassan
