artifact_uri: file:///E:/M_Hassan/AI_Work/StackOverflow_skills_analysis/Dev_skills_recommendations-anlytics/notebooks/../models/runs/907184637109318169/f0c59d4307f649b1a93cd2fb922448a4/artifacts
end_time: 1691500968710
entry_point_name: ''
experiment_id: '907184637109318169'
lifecycle_stage: active
run_id: f0c59d4307f649b1a93cd2fb922448a4
run_name: 1.basic_model_with_original_features
run_uuid: f0c59d4307f649b1a93cd2fb922448a4
source_name: ''
source_type: 4
source_version: ''
start_time: 1691500968672
status: 3
tags: []
user_id: mhassan
