artifact_uri: file:///D:/protofolio_projects/Dev_skills_recommendations-anlytics/notebooks/../models/runs/735982700926372623/91321ce64e8646d7a8e28dac0a5d8deb/artifacts
end_time: 1692264336877
entry_point_name: ''
experiment_id: '735982700926372623'
lifecycle_stage: active
run_id: 91321ce64e8646d7a8e28dac0a5d8deb
run_name: Logistic-Regression_Original-Features_1.0.0
run_uuid: 91321ce64e8646d7a8e28dac0a5d8deb
source_name: ''
source_type: 4
source_version: ''
start_time: 1692264336843
status: 3
tags: []
user_id: mahmo
