artifact_location: file:///D:/protofolio_projects/Dev_skills_recommendations-anlytics/notebooks/../models/runs/0
creation_time: 1692264336703
experiment_id: '0'
last_update_time: 1692264336703
lifecycle_stage: active
name: Default
