artifact_location: file:///E:/M_Hassan/AI_Work/StackOverflow_skills_analysis/Dev_skills_recommendations-anlytics/notebooks/../models/runs/0
creation_time: 1691500968495
experiment_id: '0'
last_update_time: 1691500968495
lifecycle_stage: active
name: Default
