artifact_location: file:///E:/M_Hassan/AI_Work/StackOverflow_skills_analysis/dev_skills_recommendations-anlytics/notebooks/../models/runs/391017000133266862
creation_time: 1689773930970
experiment_id: '391017000133266862'
last_update_time: 1689773930970
lifecycle_stage: active
name: skills_rec_analysis
